### ISSUE TITLE
Monitoring signals from NM

### ISSUE THREAD

**Issue by toxxin** [KevinVoell/network_manager#18]
Hello,

First of all, thanks for your crate, it simplifies the work with zbus for me! Examples are great and a very good start to interact with the network.
After basic network configuration, I wanted to add one simple signal subscription: Device StateChanged, and I could not set it properly.

Here is what I see from dbus-monitor:

```
$ dbus-monitor --system "type='signal',interface='org.freedesktop.NetworkManager.Device'"

signal time=1727072584.961034 sender=:1.5 -> destination=(null destination) serial=38369 path=/org/freedesktop/NetworkManager/Devices/6; interface=org.freedesktop.NetworkManager.Device; member=StateChanged
   uint32 110
   uint32 100
   uint32 39
signal time=1727072585.724359 sender=:1.5 -> destination=(null destination) serial=38413 path=/org/freedesktop/NetworkManager/Devices/6; interface=org.freedesktop.NetworkManager.Device; member=StateChanged
   uint32 30
   uint32 110
   uint32 39
```

So, I can see the StateChanged signal when I enable/disable a certain wifi connection (e.g. nmcli con up wtest, nmcli con down wtest).

My assumption is that I can do similar from rust, and indeed there is proxy macro for Device, and I'm trying to do something like this:

```
let connection = zbus::Connection::system().await.unwrap();

// Get the proxy for NetworkManager
let nm = NetworkManagerProxy::new(&connection).await?;

// get device by iface
let device_path = nm.get_device_by_ip_iface("wlan0").await?;

let device_proxy = DeviceProxy::new_from_path(device_path, &connection).await?;

let mut stream = device_proxy.receive_device_state_changed().await?;

// Process each signal in the stream
while let Some(signal) = stream.next().await {
    let new_state: u32 = signal.args().expect("Failed to unwrap the signal args").new_state;
    info!("Received StateChanged signal: {}", new_state);
}
```

Unfortunately, there is nothing there, and apparently stream.next() is never invoked. Could you please clarify if I did something wrong or something is missing? Frankly speaking, without an example (or having only a zbus example) it is not so easy to understand how to properly work and configure signals on the dbus interface.

Thank you!

**Comment by lincemiope** [comment]
Hi, I am trying to do the same. Have you found a solution yourself?

**Comment by toxxin** [comment]
Nope, I haven't tried to debug it yet, and I'm just polling the status of network properties now.

**Comment by lincemiope** [comment]
I made it to work by changing the name of the signal from "state_changed" to "StateChanged" in network manager source code file device.rs.

**Comment by toxxin** [comment]
Nice! Could you please open PR? Maybe the @KevinVoell  will merge it soon.

**Comment by KevinVoell** [comment]
Hi @lincemiope thank you for the PR, sorry I didn't see this issue sooner.  I've merged your PR and will publish a new crate shortly.
